<a href="https://colab.research.google.com/github/vijayareddy2002/stat_lab/blob/main/calab_multino.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def multiplication_matrix(a,b):
    if(len(a[0])==len(b)):
        c=np.zeros((len(a),len(b[0])),dtype='float')
        for i in range(0,len(a)):
            for j in range(0,len(b[0])):
                sum=0
                for s in range(0,len(a[0])):
                      sum+=(a[i][s])*(b[s][j])
                c[i][j]=sum
    return c

In [ ]:
#transpose
import numpy as np
def transpose_matrix(a):
    t=np.zeros((len(a[0]),len(a)),dtype='float')
    for i in range(0,len(a[0])):
          for j in range(0,len(a)):
                t[i][j]=a[j][i]
    return t

In [ ]:
def inverse(l):
  if(len(l)==3 and len(l[0]==3)):
    r=len(l)
    c=len(l[0])
    adj=[]
    det=0
    for i in range(0,r):
            g=[]
            for j in range(0,c):
                    z=[]
                    for k in range(0,r):
                          for s in  range(0,c):
                                  if i!=k and s!=j:
                                         z.append(l[k][s])
                    if((i+j)%2==0):
                            d=1*(z[0]*z[3]-z[1]*z[2])
                            g.append(d)
                    else:
                        d=-1*(z[0]*z[3]-z[1]*z[2])
                        g.append(d)
            adj.append(g)
    det=det+adj[0][0]*l[0][0]+(adj[0][1]*l[0][1])+(adj[2][0]*l[2][0]);
    print("det is :",det);
    k=transpose_matrix(adj)/det
    return k
  else:
    return np.linalg.inv(l)

In [ ]:
import numpy as np
import math
import scipy.stats as stats
a=[[1,1,1,1,1,1,1,1,1,1,1,1],
[9,8,7,14,12,10,7,4,6,5,7,6],
[62,58,64,60,63,57,55,56,59,61,57,60],]
y=np.array([[100,110,105,94,95,99,104,108,105,98,105,110]])
ytrans=transpose_matrix(y)
print("ytarns is :")
print(ytrans)
trans=np.array(a)
atrans=transpose_matrix(trans)
z1=multiplication_matrix(trans,atrans)
print(" xtranspose x is :")
print(z1)
print("invrse of xtransposex is :")
d=inverse(z1)
print(d)
c1=multiplication_matrix(trans,ytrans)
print("x transpose y is :",c1)
#print(d,c1)
beta=multiplication_matrix(d,c1)
print("beta values is :",beta)
q=np.array([100,110,105,94,95,99,104,108,105,98,105,110])
ycap=[]
error=[]
for i in range(0,len(trans)):
  s=133.460-1.2485*(trans[i][1])-0.3510*(trans[i][2])
  e=q[i]-s
  ycap.append(s)
  error.append(e)
print(error)
sse=[i**2 for i in error]
s=0
for i in sse:
  s=s+i
sse_1=s
mean_y=q.mean()
print(mean_y)
s=0
for i in q:
   s=s+(mean_y-i)**2
sst=s
ssr=sst-sse_1
print(ssr)
rsquare=ssr/sst
if(rsquare>0.90):
  print("good fit")
else:
  print("bad fit")
#anova testing
msr=ssr/(len(beta)-1)
mse=sse_1/(len(q)-len(beta)) 
F=msr/mse
ft_tr=stats.f.ppf(1-0.05,len(beta)-1,len(q)-len(beta))
#get table value and decide by anova
#Beta checking
t=[]
for i in range(len(beta)):
   p=mse*(z1[i][i])
   h=math.pow(p,0.5)
   t.append(h)
print(t)
tablevalue2=stats.t.ppf(1-(0.05)/2,)
#if()
#get table value of t and compare and print -- then gets complete

ytarns is :
[[100.]
 [110.]
 [105.]
 [ 94.]
 [ 95.]
 [ 99.]
 [104.]
 [108.]
 [105.]
 [ 98.]
 [105.]
 [110.]]
 xtranspose x is :
[[1.2000e+01 9.5000e+01 7.1200e+02]
 [9.5000e+01 8.4500e+02 5.6630e+03]
 [7.1200e+02 5.6630e+03 4.2334e+04]]
invrse of xtransposex is :
det is : 90542.0
[[ 4.08944026e+01  1.14046520e-01 -7.03043891e-01]
 [ 1.14046520e-01  1.17514524e-02 -3.49009300e-03]
 [-7.03043891e-01 -3.49009300e-03  1.23147269e-02]]
x transpose y is : [[ 1233.]
 [ 9636.]
 [73094.]]
beta values is : [[133.46048243]
 [ -1.24850346]
 [ -0.35100837]]
[-31.860500000000002, -11.015000000000015, 66.41699999999999]
102.75
-5217.389574249999
bad fit
[86.00495779701694, 721.7075000180897, 5108.313199920079]


TypeError: ignored

In [ ]:
y=np.array([[1,2,3,4,5]])
print(len(y[0]))

5


In [ ]:
def ycapvals(beta,pos,x1,x2,x3):
  y1cap=[]
  print(pos[0])
  for i in range(0,len(x1)):
     z=pos[0]+pos[1]*(x1[i])+pos[2]*(x2[i])+pos[3]*(x3[i])
     y1cap.append(z)
  return y1cap

In [ ]:
#multi variate linear regression
import scipy.stats as sc
import math
xtrans=np.array([[1,1,1,1,1,1,1,1,1,1,1,1],[9,8,7,14,12,10,7,4,6,5,7,6],[62,58,64,60,63,57,55,56,59,61,57,60],[1,1.3,1.2,0.8,0.8,0.9,1.0,1.2,1.1,1.0,1.2,1.2]])
ytrans=np.array([[10,12,11,9,9,10,11,12,11,10,11,12],[100,110,105,94,95,99,104,108,105,98,103,110]])
y=transpose_matrix(ytrans)
print("y value is :",y)
x=transpose_matrix(xtrans)
print(x)
multi1=multiplication_matrix(xtrans,x)
print("multi1:",multi1)
inv1=inverse(multi1)
print("inverse:",inv1)
multi2=multiplication_matrix(xtrans,y)
print("multi2 :")
print(multi2)
beta=multiplication_matrix(inv1,multi2)
print("beta:",beta)
i=0
j=1
row=0
k=0
x1=[9,8,7,14,12,10,7,4,6,5,7,6]
x2=[62,58,64,60,63,57,55,56,59,61,57,60]
x3=[1,1.3,1.2,0.8,0.8,0.9,1.0,1.2,1.1,1.0,1.2,1.2]
#try in loop by netx week--tried with function
res=[]
for i in range(0,len(beta[0])):
  l=[]
  for j in range(0,len(beta)):
      l.append(beta[j][i])
  k=ycapvals(beta,l,x1,x2,x3)
  res.append(k)
print(res)
res=np.array(res)
re=transpose_matrix(res)
print(re)
print(re.shape)
print(y.shape)
yerror=np.subtract(y,re)
print("substraction:",yerror)
yerror=transpose_matrix(yerror)
btrans=transpose_matrix(beta)
print("beta trans:",btrans)
for i in range(0,len(yerror)):
  sse=[j**2 for j in yerror[i]]
  ssee=sum(sse)
  u=np.array(yerror[i])
  z=u.mean()
  sst=[(z-k)**2 for k in sse]
  sstt=sum(sst)
  ssr=sstt-ssee
  r=ssr/sstt
  if(r>0.90):
    print("y",(i+1)," is a good fit")
  else:
    print("y",(i+1)," is a bad fit")
  #using anova
  print("using anova:")
  msr=ssr/(len(btrans[i])-1)
  mse=ssee/(len(u)-len(btrans[i]))
  print("msr for y",(i+1),msr)
  print("mse for y",(i+1),mse)
  fcal=msr/mse
  print("faclculated:",fcal)
  t=sc.f.ppf(1-0.05,len(btrans[i])-1,len(u)-len(btrans[i]))
  print("table value is :",t)
  if(fcal>t):
    print("we reject the y",(i+1),"according to anova")
  else:
    print("we accept the y",(i+1),"acccording to anova")
  #for variables in beta of y1 and y2 each variable contributing or not
  t=[]
  for v in range(0,len(btrans[i])):
           d=mse*(inv1[v][v])
           s=math.pow(d,0.5)
           res=btrans[i][v]/s
           t.append(res)
  t_beta=sc.t.ppf(1-(0.05/2),len(u)-len(btrans[i]))
  for m in  range(0,len(t)):
      if(abs(t[m])>t_beta):
            print("y",(i+1),": beta ",m ,"is contributiing to model")
      else:
        print("y",(i+1),": beta ",m,"is not contributing to model")


y value is : [[ 10. 100.]
 [ 12. 110.]
 [ 11. 105.]
 [  9.  94.]
 [  9.  95.]
 [ 10.  99.]
 [ 11. 104.]
 [ 12. 108.]
 [ 11. 105.]
 [ 10.  98.]
 [ 11. 103.]
 [ 12. 110.]]
[[ 1.   9.  62.   1. ]
 [ 1.   8.  58.   1.3]
 [ 1.   7.  64.   1.2]
 [ 1.  14.  60.   0.8]
 [ 1.  12.  63.   0.8]
 [ 1.  10.  57.   0.9]
 [ 1.   7.  55.   1. ]
 [ 1.   4.  56.   1.2]
 [ 1.   6.  59.   1.1]
 [ 1.   5.  61.   1. ]
 [ 1.   7.  57.   1.2]
 [ 1.   6.  60.   1.2]]
multi1: [[1.2000e+01 9.5000e+01 7.1200e+02 1.2700e+01]
 [9.5000e+01 8.4500e+02 5.6630e+03 9.6600e+01]
 [7.1200e+02 5.6630e+03 4.2334e+04 7.5240e+02]
 [1.2700e+01 9.6600e+01 7.5240e+02 1.3750e+01]]
inverse: [[ 5.48122405e+01 -3.05443019e-01 -7.05023338e-01 -9.90182539e+00]
 [-3.05443019e-01  2.43950451e-02 -3.43043164e-03  2.98445219e-01]
 [-7.05023338e-01 -3.43043164e-03  1.23150084e-02  1.40827427e-03]
 [-9.90182539e+00  2.98445219e-01  1.40827427e-03  7.04463918e+00]]
multi2 :
[[  128.   1231. ]
 [  987.   9622. ]
 [ 7580.  72980. ]
 [  137.3  1

In [ ]:
y1=eval(10.897-0.045x1-0.087x2+5.035x3)
print(y1)

SyntaxError: ignored

In [ ]:
s=np.dot(xtrans,x)
print("s:",s)
ins=np.linalg.inv(s)
print("ins:",ins)
z=np.dot(xtrans,y)
print(z)
print(np.dot(ins,z))

s: [[1.2000e+01 9.5000e+01 7.1200e+02 1.2700e+01]
 [9.5000e+01 8.4500e+02 5.6630e+03 9.6600e+01]
 [7.1200e+02 5.6630e+03 4.2334e+04 7.5240e+02]
 [1.2700e+01 9.6600e+01 7.5240e+02 1.3750e+01]]
ins: [[ 5.48122405e+01 -3.05443019e-01 -7.05023338e-01 -9.90182539e+00]
 [-3.05443019e-01  2.43950451e-02 -3.43043164e-03  2.98445219e-01]
 [-7.05023338e-01 -3.43043164e-03  1.23150084e-02  1.40827427e-03]
 [-9.90182539e+00  2.98445219e-01  1.40827427e-03  7.04463918e+00]]
[[  128.   1231. ]
 [  987.   9622. ]
 [ 7580.  72980. ]
 [  137.3  1312. ]]
[[ 1.08969952e+01  9.10971989e+01]
 [-4.49402884e-02 -6.40072328e-02]
 [-8.77035871e-02 -2.94373672e-01]
 [ 5.03545972e+00  2.78353035e+01]]


NameError: ignored