<a href="https://colab.research.google.com/github/vijayareddy2002/stat_lab/blob/main/linear__discriminant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
'''n=int(input("enter no of columns"))
x=int(input("enter no of rows "))
ar=[]
o=[ 1 for i in range(0,x)]
ar.append(o)
for i in range(0,n):
  l=input()
  s=l.split(" ")
  r=[ float(i) for i in s]
  ar.append(r)'''
ar=[[1,1,1,1,1,1,1,1,1,1],[1300,1260,1220,1118,1060,1140,1100,1020,980,940],[2.7,3.7,2.9,2.5,3.9,2.1,3.5,3.3,2.3,3.1]]
y=input()
b=list(y.split(" "))
c=[int(i) for i in b]
z=np.array([c])
k=z.transpose()
atrans=np.array(ar)
print("x is ")
print(atrans,end=" ")
print(atrans.shape)
a=atrans.transpose()
print("transpose")
print(a)
print("shape a")
print(a.shape)
multi_1=atrans.dot(a)
print("multi1")
print(multi_1)
inv1=np.linalg.inv(multi_1)
print(inv1)
multi_2=atrans.dot(k)
print(multi_2)
beta=inv1.dot(multi_2)
print("beta values")
print(beta)
print("discriminant function")
print("give values to differentiate: ")
ad=input()
ad=[float(i) for i in ad.split(" ")]
s1=beta[0]
for i in range(1,len(beta)):
  s1=s1+(beta[i]*ad[i-1])
print(s1)
if( s1<=0 and s1!=0.9):
  print("belongs to 1")
else:
  print("belongs to 2")



1 1 1 1 1 0 0 0 0 0
x is 
[[1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
  1.000e+00 1.000e+00 1.000e+00]
 [1.300e+03 1.260e+03 1.220e+03 1.118e+03 1.060e+03 1.140e+03 1.100e+03
  1.020e+03 9.800e+02 9.400e+02]
 [2.700e+00 3.700e+00 2.900e+00 2.500e+00 3.900e+00 2.100e+00 3.500e+00
  3.300e+00 2.300e+00 3.100e+00]] (3, 10)
transpose
[[1.000e+00 1.300e+03 2.700e+00]
 [1.000e+00 1.260e+03 3.700e+00]
 [1.000e+00 1.220e+03 2.900e+00]
 [1.000e+00 1.118e+03 2.500e+00]
 [1.000e+00 1.060e+03 3.900e+00]
 [1.000e+00 1.140e+03 2.100e+00]
 [1.000e+00 1.100e+03 3.500e+00]
 [1.000e+00 1.020e+03 3.300e+00]
 [1.000e+00 9.800e+02 2.300e+00]
 [1.000e+00 9.400e+02 3.100e+00]]
shape a
(10, 3)
multi1
[[1.0000000e+01 1.1138000e+04 3.0000000e+01]
 [1.1138000e+04 1.2533524e+07 3.3417000e+04]
 [3.0000000e+01 3.3417000e+04 9.3300000e+01]]
[[ 1.24703969e+01 -8.67911162e-03 -9.01200808e-01]
 [-8.67911162e-03  7.81147031e-06 -7.10133664e-06]
 [-9.01200808e-01 -7.10133664e-06  3.03036759e-0

In [ ]:
z=(-3.5070)+(0.0032)*(1000)+(0.2395*(2.9))
print(z)

0.38755000000000006


In [ ]:
#fischers
from math import log
ar=[[2.95,2.53,3.57,3.16,2.58,2.16,3.27,],[6.63,7.79,5.65,5.47,4.46,6.22,3.52]]
d=np.array(ar) #an use data frame
d1=d.transpose()
y=[1,1,1,1,0,0,0,]
a=np.array(ar)
b=np.array([y])
x1=[]
x2=[]
for i in range(0,len(y)):
  if(b[0][i]==1):
        x1.append(d1[i])
  else:
    x2.append(d1[i])
print("a is :")
x_1=np.array(x1)
print(x_1)
print("b is :")
x_2=np.array(x2)
print(x_2)
mean1=np.mean(x_1,axis=0)
mean2=np.mean(x_2,axis=0)
print("mean1:")
print(mean1)
print("mean2")
print(mean2)
print("mean x:")
mean_x=np.mean(d1,axis=0)
print(mean_x)
exmu=np.subtract(d1,mean_x)
print(exmu)
c1=((exmu.transpose()).dot(exmu))/len(ar[0])
print(c1)
cinv=np.linalg.inv(c1)
xk=np.array([2.81,5.46])
def fish(m,c,prob,xk):
   f=m.dot(c)
   xktrans=xk.transpose()
   res1=f.dot(xktrans)
   #print(res1)
   d=m.transpose()
   z=(f.dot(d))*(0.5)
   #print(z)
   k=np.subtract(res1,z)
   k=k+log(prob)
   return k
f1=fish(mean1,cinv,len(x_1)/len(d1),xk)
f2=fish(mean2,cinv,len(x_2)/len(d1),xk)
print(f1)
print(f2)
if(f1>f2):
  print("belongs to f1")
else:
  print("belongs to f2")
  

a is :
[[2.95 6.63]
 [2.53 7.79]
 [3.57 5.65]
 [3.16 5.47]]
b is :
[[2.58 4.46]
 [2.16 6.22]
 [3.27 3.52]]
mean1:
[3.0525 6.385 ]
mean2
[2.67       4.73333333]
mean x:
[2.88857143 5.67714286]
[[ 0.06142857  0.95285714]
 [-0.35857143  2.11285714]
 [ 0.68142857 -0.02714286]
 [ 0.27142857 -0.20714286]
 [-0.30857143 -1.21714286]
 [-0.72857143  0.54285714]
 [ 0.38142857 -2.15714286]]
[[ 0.20598367 -0.23093265]
 [-0.23093265  1.69216327]]
43.828180992167894
43.863020178214434
belongs to f2
