<a href="https://colab.research.google.com/github/vijayareddy2002/stat_lab/blob/main/Manova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#manova table
#reading information---
#t=int(input("enter no of treaments"))
import math
import scipy.stats as stats
l=[[[9,3],[6,2],[9,7]],[[0,4],[2,0]],[[3,8],[1,9],[2,7]]]
print(l)
import numpy as np
a=np.array(l)
a_t=a.transpose()
'''for i in range(0,t):
    s=[]
    z=int(input("enter no of lists in treatmennt"))
    for k in range(0,z):
        m=input()
        g=list(m.split(" "))
        g=[int(x) for x in g]
        s.append(g)
    l.append(s)
print(l)'''
s=0
yi=[]
for i in range(0,len(l)):
    s1=0
    s2=0
    v=[]
    for j in range(0,len(l[i])):
        s1=s1+l[i][j][0]
        s2=s2+l[i][j][1]
    v.append(s1/len(l[i]))
    v.append(s2/len(l[i]))
    yi.append(v)
print(yi)
ybar=[]
s2=0
f=[]
f1=[]
for i in  range(0,len(l)):
    for j in range(0,len(l[i])):
               f.append(l[i][j][0])        
               f1.append(l[i][j][1])
#print(f)
#print(f1)
z=yi[0]
print(z)
ybar.append(sum(f)/len(f))
ybar.append(sum(f1)/len(f))
print(ybar)
ssee=[]
ssrr=[]
sstt=[]
for b in range(0,len(ybar)):
   sse=0
   sst=0
   for i in range(0,len(l)):
      for k in range(0,len(l[i])):
          sse=sse+(l[i][k][b]-yi[i][b])**2
          sst=sst+(l[i][k][b]-ybar[b])**2
   ssee.append(sse)
   sstt.append(sst)
   ssr=sst-sse
   ssrr.append(ssr)
print(ssee)
print(ssrr)
print(sstt)
#cross product calculation
ssey=0
ssty=0
for i in range(0,len(l)):
    for j in range(0,len(l[i])):
        ssey=ssey+(l[i][j][0]*l[i][j][1])-(yi[i][0]*yi[i][1])
        ssty=ssty+(l[i][j][0]*l[i][j][1])-(ybar[0]*ybar[1])
print(ssey)
print(ssty)
ssry=ssty-ssey
print(ssry)
print("REGression B")
B=np.array([[ssrr[0],ssry],[ssry,ssrr[1]]])
W=np.array([[ssee[0],ssey],[ssey,ssee[1]]])
T=np.array([[sstt[0],ssty],[ssty,sstt[1]]])
print(B)
print(W)
print(T)
numb=len(l[0])+len(l[1])+len(l[2])
dr=len(l)-1
de=len(l[0])+len(l[1])+len(l[2])-(len(l)-1)
dt=len(l[0])+len(l[1])+len(l[2])-1
d1=np.linalg.det(W)
d2=np.linalg.det(T)
lambstar=d1/d2
print(lambstar,end=" ")
temp=math.pow(lambstar,0.5)
Fcalt=(numb-len(l)-1)*((1-temp))
Fcalt1=Fcalt/(temp*(len(l)-1))
print(Fcalt1,end=" ")
Ftab=stats.f.ppf(1-0.05,2*(dr),2*(((dt+1)-(dr))))
print(Ftab,end=" ")
if(Fcalt1 > Ftab):
    print("\nreject h0")
else:
  print("accepted h0")

[[[9, 3], [6, 2], [9, 7]], [[0, 4], [2, 0]], [[3, 8], [1, 9], [2, 7]]]
[[8.0, 4.0], [1.0, 2.0], [2.0, 8.0]]
[8.0, 4.0]
[4.0, 5.0]
[10.0, 24.0]
[78.0, 48.0]
[88.0, 72.0]
1.0
-11.0
-12.0
REGression B
[[ 78. -12.]
 [-12.  48.]]
[[10.  1.]
 [ 1. 24.]]
[[ 88. -11.]
 [-11.  72.]]
0.0384553499597747 8.198859563778381 3.259166726901249 
reject h0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if __name__ == '__main__':


In [ ]:
#