<a href="https://colab.research.google.com/github/vijayareddy2002/stat_lab/blob/main/PCA_factor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#reading inputs
import numpy as np
t=int(input("enter no of columns"))
#l=[[2,1,0,-1],[4,3,1,0.5]]
l=[]
for i in range(0,t):
  s=input()
  k=[float(i) for i in s.split(" ")]
  l.append(k)
print(l)
a=np.array(l)
a=np.transpose(a)
mu=np.mean(a,axis=0)
print("mean matrix:")
print(mu)
dif=np.subtract(a,mu)
c=(np.dot(np.transpose(dif),dif)/len(l[0]))
print(c)
eigval,eigvec=np.linalg.eig(c)
print("before eigen values")
print(eigval)
print(eigvec)
ind=eigval.argsort()[::-1]
print("after sorting")
eigval=eigval[ind]
eigvec=eigvec[:,ind]
print("new eigen vals ")
print(eigval)
print(eigvec)
s_1=sum(eigval)
print(s_1)
t=0
finaleig=[]
thres=float(input("enter threshold"))
for i in range(0,len(eigval)):
    g=sum(eigval[0:i+1])
    h=(g/s_1)*100
    if h <= thres:
        t=t+1
finaleig.append(eigvec[:t+1])
print(finaleig)
#multiplying with x1 and x2 and get reducted values
red=[]
for i in range(0,t+1):
    z1=[]
    for j in range(0,len(a)):
         sum_1=0
         for k in range(0,len(a[j])):
                 sum_1+=eigvec[i][k]*a[j][k]
         z1.append(sum_1)
    red.append(z1)
print(red)

enter no of columns3
90 90 60 60 30
60 90 60 60 30
90 30 60 90 30
[[90.0, 90.0, 60.0, 60.0, 30.0], [60.0, 90.0, 60.0, 60.0, 30.0], [90.0, 30.0, 60.0, 90.0, 30.0]]
mean matrix:
[66. 60. 60.]
[[504. 360. 180.]
 [360. 360.   0.]
 [180.   0. 720.]]
before eigen values
[ 44.81966028 910.06995304 629.11038668]
[[ 0.6487899  -0.65580225 -0.3859988 ]
 [-0.74104991 -0.4291978  -0.51636642]
 [-0.17296443 -0.62105769  0.7644414 ]]
after sorting
new eigen vals 
[910.06995304 629.11038668  44.81966028]
[[-0.74104991 -0.4291978  -0.51636642]
 [-0.17296443 -0.62105769  0.7644414 ]
 [ 0.6487899  -0.65580225 -0.3859988 ]]
1584.0000000000005
enter threshold95.0
[array([[-0.74104991, -0.4291978 , -0.51636642],
       [-0.17296443, -0.62105769,  0.7644414 ]])]
[[-138.91933759003626, -120.81328642320372, -101.19684765766459, -116.68784018931119, -50.598423828832296], [15.969465958778883, -48.5287486730182, -1.7748431526436406, 21.158398819382725, -0.8874215763218203]]


enter no of columns2
2 1 0 -1
4 3 1 0.5
[[2.0, 1.0, 0.0, -1.0], [4.0, 3.0, 1.0, 0.5]]
mean matrix:
[0.5   2.125]
[[1.25     1.5625  ]
 [1.5625   2.046875]]
before eigen values
[0.03593674 3.26093826]
[[-0.78964958 -0.6135581 ]
 [ 0.6135581  -0.78964958]]
after sorting
new eigen vals 
[3.26093826 0.03593674]
[[ 0.6135581  -0.78964958]
 [-0.78964958 -0.6135581 ]]
3.2968750000000004
enter threshold95.0
[array([[ 0.6135581 , -0.78964958]])]
[[-1.9314820988922412, -1.7553906259205196, -0.789649576474399, -1.008382891739877]]

In [ ]:
#factor analysis
import numpy as np
import math 
'''t=int(input("enter the no of columns:"))
l=[]
for i in range(0,t):
  d=input()
  d=[float(i) for i in d.split(" ")]
  l.append(d)'''
l=[[3,7,10,3,10],[6,3,9,9,6],[5,3,8,7,5]]
a=np.array(l)
mean_1=np.mean(a,axis=1)
print(mean_1)
standard_devia=np.std(a,axis=1)
print(standard_devia)
a=np.transpose(a)
sd_matrix=(np.subtract(a,mean_1))/standard_devia
print(sd_matrix)
print("varience-covarience matrix:")
c=np.dot(np.transpose(sd_matrix),sd_matrix)/len(l[0])
print(c)
eigval,eigvec=np.linalg.eig(c)
print("eigen values:")
print(eigval)
print("eigen vectors")
print(eigvec)
indexes=eigval.argsort()[::-1]
eigval=eigval[indexes]
eigvec=eigvec[:,indexes]
print("after the descending order:")
print(eigval)
print(eigvec)
print("deciding factor:")
s_1=sum(eigval)
print("sum of lambdas")
print(s_1)
t=0
finaleig=[]
thres=float(input("enter threshold"))
for i in range(0,len(eigval)):
    g=sum(eigval[0:i+1])
    h=(g/s_1)*100
    if h <= thres:
        t=t+1
print("no of lambda vals:",t)
z1=[]
for i in range(0,t+1):
   print("for factor",(i+1))
   z=math.pow(eigval[i],0.5)
   z1.append(np.dot(z,eigvec[i]))
k=np.array(z1)
k=np.transpose(k)
print(k)
p=[]
for i in range(0,len(k)):
  s_3=0
  for j in range(0,len(k[i])):
    s_3+=k[i][j]**2
  p.append(s_3)
k_1=sum(p)
print("sum of communalities")
print(k_1)
for i in range(0,t+1):
  y=eigval[i]
  print("varience of explained",(i+1))
  print(y/k_1)
'''for i in range(0,len(mean_1)):
  for j in range(0,len(a))'''

[6.6 6.6 5.6]
[3.13687743 2.24499443 1.74355958]
[[-1.14763808 -0.26726124 -0.3441236 ]
 [ 0.12751534 -1.60356745 -1.49120227]
 [ 1.08388041  1.06904497  1.3764944 ]
 [-1.14763808  1.06904497  0.80295507]
 [ 1.08388041 -0.26726124 -0.3441236 ]]
varience-covarience matrix:
[[ 1.         -0.05111986  0.08044857]
 [-0.05111986  1.          0.98102294]
 [ 0.08044857  0.98102294  1.        ]]
eigen values:
[0.01023054 1.00830633 1.98146313]
eigen vectors
[[-0.09360247 -0.99538347  0.0212208 ]
 [-0.70330551  0.08119286  0.70623585]
 [ 0.70469847 -0.05118071  0.70765853]]
after the descending order:
[1.98146313 1.00830633 0.01023054]
[[ 0.0212208  -0.99538347 -0.09360247]
 [ 0.70623585  0.08119286 -0.70330551]
 [ 0.70765853 -0.05118071  0.70469847]]
deciding factor:
sum of lambdas
3.0
enter threshold99.0
no of lambda vals: 1
for factor 1
for factor 2
[[ 0.02987135  0.7091629 ]
 [-1.4011461   0.08152937]
 [-0.13175901 -0.70622041]]
sum of communalities
2.98976945999714
varience of explained 1


'for i in range(0,len(mean_1)):\n  for j in range(0,len(a))'