<a href="https://colab.research.google.com/github/vijayareddy2002/stat_lab/blob/main/PCA_cs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#reading inputs
import numpy as np
t=int(input("enter no of columns"))
#l=[[2,1,0,-1],[4,3,1,0.5]]
l=[]
for i in range(0,t):
  s=input()
  k=[float(i) for i in s.split(" ")]
  l.append(k)
print(l)
a=np.array(l)
a=np.transpose(a)
mu=np.mean(a,axis=0)
print("mean matrix:")
print(mu)
dif=np.subtract(a,mu)
c=(np.dot(np.transpose(dif),dif)/len(l[0]))
print(c)
eigval,eigvec=np.linalg.eig(c)
print("before eigen values")
print(eigval)
print(eigvec)
ind=eigval.argsort()[::-1]
print("after sorting")
eigval=eigval[ind]
eigvec=eigvec[ind]
print("new eigen vals ")
print(eigval)
print(eigvec)
s_1=sum(eigval)
print(s_1)
t=0
finaleig=[]
thres=float(input("enter threshold"))
for i in range(0,len(eigval)):
    g=sum(eigval[0:i+1])
    h=(g/s_1)*100
    if h <= thres:
        t=t+1
finaleig.append(eigvec[:t+1])
print(finaleig)
#multiplying with x1 and x2 and get reducted values
red=[]
for i in range(0,t+1):
    z1=[]
    for j in range(0,len(a)):
         sum_1=0
         for k in range(0,len(a[j])):
                 sum_1+=eigvec[i][k]*a[j][k]
         z1.append(sum_1)
    red.append(z1)
print(red)

enter no of columns3
90 90 60 60 30
60 90 60 60 30
90 30 60 90 30
[[90.0, 90.0, 60.0, 60.0, 30.0], [60.0, 90.0, 60.0, 60.0, 30.0], [90.0, 30.0, 60.0, 90.0, 30.0]]
mean matrix:
[66. 60. 60.]
[[504. 360. 180.]
 [360. 360.   0.]
 [180.   0. 720.]]
before eigen values
[ 44.81966028 910.06995304 629.11038668]
[[ 0.6487899  -0.65580225 -0.3859988 ]
 [-0.74104991 -0.4291978  -0.51636642]
 [-0.17296443 -0.62105769  0.7644414 ]]
after sorting
new eigen vals 
[910.06995304 629.11038668  44.81966028]
[[-0.74104991 -0.4291978  -0.51636642]
 [-0.17296443 -0.62105769  0.7644414 ]
 [ 0.6487899  -0.65580225 -0.3859988 ]]
1584.0000000000005
enter threshold95.0
[array([[-0.74104991, -0.4291978 , -0.51636642],
       [-0.17296443, -0.62105769,  0.7644414 ]])]
[[-138.91933759003626, -120.81328642320372, -101.19684765766459, -116.68784018931119, -50.598423828832296], [15.969465958778883, -48.5287486730182, -1.7748431526436406, 21.158398819382725, -0.8874215763218203]]


enter no of columns2
2 1 0 -1
4 3 1 0.5
[[2.0, 1.0, 0.0, -1.0], [4.0, 3.0, 1.0, 0.5]]
mean matrix:
[0.5   2.125]
[[1.25     1.5625  ]
 [1.5625   2.046875]]
before eigen values
[0.03593674 3.26093826]
[[-0.78964958 -0.6135581 ]
 [ 0.6135581  -0.78964958]]
after sorting
new eigen vals 
[3.26093826 0.03593674]
[[ 0.6135581  -0.78964958]
 [-0.78964958 -0.6135581 ]]
3.2968750000000004
enter threshold95.0
[array([[ 0.6135581 , -0.78964958]])]
[[-1.9314820988922412, -1.7553906259205196, -0.789649576474399, -1.008382891739877]]